"""Unit & integration tests for section detection fallback on unstructured CVs without headings.

Verifies:
1. Section detection failure or heading-less CVs assign `section="unknown"` and `section_confidence=0.0`.
2. 100% exact span fidelity is maintained across all chunks.
3. Full-text vector retrieval successfully finds candidate evidence despite missing sections.
4. Trust tier is degraded to "low" and `SECTION_DETECTION_LOW_CONFIDENCE` diagnostic is emitted.
5. No silent/implicit assignment to `experience` occurs anywhere in the pipeline.
"""

import pytest

from src.chunking.section_detector import SectionDetector
from src.chunking.text_chunker import TextChunker
from src.chunking.validator import (
    ValidationStatus,
    validate_evidence_block,
    validate_evidence_blocks,
)
from src.chunking.vector_store import LocalVectorStore
from src.models.evidence import CVSection, EvidenceBlock


@pytest.fixture
def detector():
    return SectionDetector()


@pytest.fixture
def vector_store():
    return LocalVectorStore()


# Unstructured narrative CV without any headings or section dividers
UNSTRUCTURED_NARRATIVE_CV = (
    "Nguyễn Quốc Tuấn sinh năm 1996 tốt nghiệp ngành Công nghệ thông tin năm 2018.\n"
    "Tôi đã có 5 năm làm kỹ sư backend tại các công ty tài chính và thương mại điện tử.\n"
    "Hàng ngày tôi sử dụng Python, FastAPI, PostgreSQL và Redis để thiết kế các dịch vụ thanh toán.\n"
    "Tôi cũng thường xuyên triển khai các cụm Docker và Kubernetes trên hạ tầng AWS EKS.\n"
    "Ngoài ra tôi đạt chứng chỉ AWS Certified Solutions Architect và giải nhì Olympic tin học sinh viên."
)


# ==============================================================================
# 1. UNKNOWN SECTION & ZERO CONFIDENCE ASSIGNMENT
# ==============================================================================

def test_cv_without_headings_assigns_unknown_section_and_zero_confidence(detector):
    """Verify CV without headings produces chunks with section='unknown' and confidence=0.0."""
    sections = detector.detect_sections(UNSTRUCTURED_NARRATIVE_CV)

    # Must produce a single fallback section spanning the entire document
    assert len(sections) == 1
    sec = sections[0]
    assert sec.section == CVSection.UNKNOWN
    assert sec.confidence == 0.0
    assert sec.heading_span is None
    assert sec.full_char_start == 0
    assert sec.full_char_end == len(UNSTRUCTURED_NARRATIVE_CV)

    # Verify all chunks generated by TextChunker inherit section='unknown'
    chunks = TextChunker.chunk_resume(UNSTRUCTURED_NARRATIVE_CV, detector=detector)
    assert len(chunks) > 0

    for c in chunks:
        assert c["section"] == "unknown"
        assert c["section_confidence"] == 0.0
        assert c["is_heading"] is False


def test_no_silent_assignment_to_experience_under_any_fallback(detector):
    """Verify that despite containing words like 'kỹ sư backend' and 'làm việc',

    unstructured text is NEVER secretly or implicitly classified as 'experience'.
    """
    chunks = TextChunker.chunk_resume(UNSTRUCTURED_NARRATIVE_CV, detector=detector)

    for c in chunks:
        assert c["section"] != "experience", (
            f"Chunk '{c['text']}' was silently assigned to 'experience'!"
        )
        assert c["section"] == "unknown"


# ==============================================================================
# 2. EXACT SPAN FIDELITY ON HEADING-LESS CV
# ==============================================================================

def test_cv_without_headings_preserves_100_percent_span_fidelity(detector):
    """Verify raw_text[char_start:char_end] == chunk['text'] holds 100% on heading-less text."""
    chunks = TextChunker.chunk_resume(UNSTRUCTURED_NARRATIVE_CV, detector=detector)
    assert len(chunks) > 0

    for c in chunks:
        start = c["char_start"]
        end = c["char_end"]
        assert UNSTRUCTURED_NARRATIVE_CV[start:end] == c["text"]
        assert c["block_id"].startswith("blk_")


# ==============================================================================
# 3. FULL-TEXT VECTOR RETRIEVAL FALLBACK
# ==============================================================================

def test_cv_without_headings_allows_full_text_vector_retrieval(vector_store, detector):
    """Verify vector store gracefully falls back to full-text retrieval when sections are unknown."""
    chunks = TextChunker.chunk_resume(UNSTRUCTURED_NARRATIVE_CV, detector=detector)

    # Query 1: Search without specifying section -> full-text search
    py_results = vector_store.search_chunks("Python FastAPI PostgreSQL", chunks, top_k=3)
    assert len(py_results) > 0
    assert any("Python" in r["chunk"] for r in py_results)
    assert all(r["section"] == "unknown" for r in py_results)

    # Query 2: Search with target section='experience' -> triggers full-text fallback!
    exp_results = vector_store.search_chunks(
        query="Kubernetes Docker AWS",
        chunks=chunks,
        top_k=3,
        section="experience",
        fallback_to_all_sections=True,
    )
    assert len(exp_results) > 0
    assert any("Kubernetes" in r["chunk"] for r in exp_results)
    assert exp_results[0]["fallback_full_text"] is True

    # Check that retrieved results contain full offsets and block_id
    top_hit = exp_results[0]
    assert top_hit["block_id"].startswith("blk_")
    assert top_hit["char_start"] >= 0
    assert top_hit["char_end"] > top_hit["char_start"]
    assert UNSTRUCTURED_NARRATIVE_CV[top_hit["char_start"]:top_hit["char_end"]] == top_hit["chunk"]


# ==============================================================================
# 4. DIAGNOSTIC SECTION_DETECTION_LOW_CONFIDENCE & TRUST TIER DEGRADATION
# ==============================================================================

def test_cv_without_headings_emits_low_confidence_diagnostic_and_degraded_trust_tier(detector):
    """Verify validator emits SECTION_DETECTION_LOW_CONFIDENCE warning and sets trust_tier='low'."""
    blocks = TextChunker.chunk_to_evidence_blocks(UNSTRUCTURED_NARRATIVE_CV, detector=detector)
    assert len(blocks) > 0

    valid_blocks, diagnostics = validate_evidence_blocks(UNSTRUCTURED_NARRATIVE_CV, blocks)

    # Evidence is NOT discarded (is_valid is True, 0 hard errors)
    assert len(valid_blocks) == len(blocks)
    assert all(d.is_valid is True for d in diagnostics)
    assert all(len(d.errors) == 0 for d in diagnostics)

    # Diagnostics contain SECTION_DETECTION_LOW_CONFIDENCE and UNKNOWN_SECTION warnings
    for d in diagnostics:
        assert d.status == ValidationStatus.WARNING
        assert d.trust_tier == "low"
        warning_codes = [w.code for w in d.warnings]
        assert "SECTION_DETECTION_LOW_CONFIDENCE" in warning_codes
        assert "UNKNOWN_SECTION" in warning_codes


def test_single_block_validator_trust_tier_degradation():
    """Verify single EvidenceBlock validation properly assigns high, medium, and low trust tiers."""
    raw_text = "Python FastAPI Engineer with 4 years experience."

    # Case 1: Known section with high confidence -> high trust tier
    high_block = EvidenceBlock(
        block_id="blk_high",
        text="Python FastAPI Engineer",
        char_start=0,
        char_end=23,
        section="experience",
        section_confidence=0.95,
    )
    high_res = validate_evidence_block(raw_text, high_block)
    assert high_res.trust_tier == "high"
    assert high_res.status == ValidationStatus.VALID

    # Case 2: Known section with medium confidence -> medium trust tier
    med_block = EvidenceBlock(
        block_id="blk_med",
        text="Python FastAPI Engineer",
        char_start=0,
        char_end=23,
        section="experience",
        section_confidence=0.75,
    )
    med_res = validate_evidence_block(raw_text, med_block)
    assert med_res.trust_tier == "medium"

    # Case 3: Unknown section -> low trust tier
    unk_block = EvidenceBlock(
        block_id="blk_unk",
        text="Python FastAPI Engineer",
        char_start=0,
        char_end=23,
        section="unknown",
        section_confidence=0.0,
    )
    unk_res = validate_evidence_block(raw_text, unk_block)
    assert unk_res.trust_tier == "low"
    assert unk_res.is_valid is True
    assert any(w.code == "SECTION_DETECTION_LOW_CONFIDENCE" for w in unk_res.warnings)

