/** List of common Vietnamese industries */
export const VIETNAMESE_INDUSTRIES: string[] = [
  'Công nghệ thông tin',
  'Tài chính - Ngân hàng',
  'Xây dựng',
  'Y tế - Dược phẩm',
  'Vận tải - Logistics',
  'Giải trí - Truyền thông',
  'Giáo dục - Đào tạo',
  'Bất động sản',
  'Bảo hiểm',
  'Bán lẻ - Thương mại',
  'Du lịch - Khách sạn',
  'Điện tử - Viễn thông',
  'Dệt may - Da giày',
  'Dầu khí - Năng lượng',
  'Hàng không',
  'Hóa chất',
  'Luật - Tư vấn',
  'Marketing - Quảng cáo',
  'Nông nghiệp',
  'Nhà hàng - Ẩm thực',
  'Sản xuất - Chế tạo',
  'Thủy sản',
  'Thương mại điện tử',
  'Tự động hóa - Robotics',
  'Khác',
];
