import { IconDefinition } from '@ant-design/icons-angular';
import {
  AlertFill,
  AlertOutline,
  ApartmentOutline,
  AppstoreOutline,
  ArrowLeftOutline,
  ArrowRightOutline,
  AuditOutline,
  BankOutline,
  BellOutline,
  BookFill,
  BookOutline,
  BulbFill,
  BulbOutline,
  CalendarOutline,
  CarryOutOutline,
  CheckCircleFill,
  CheckCircleOutline,
  CheckOutline,
  ClearOutline,
  ClockCircleOutline,
  CloseCircleFill,
  CloseCircleOutline,
  CloseOutline,
  CloudUploadOutline,
  DashboardOutline,
  DeleteOutline,
  DollarOutline,
  DownOutline,
  EditOutline,
  EnvironmentOutline,
  ExportOutline,
  EyeInvisibleOutline,
  EyeOutline,
  FilePdfOutline,
  FileSearchOutline,
  FileTextOutline,
  FileWordOutline,
  FilterOutline,
  FundProjectionScreenOutline,
  GlobalOutline,
  HeartFill,
  HeartOutline,
  HomeOutline,
  InboxOutline,
  InfoCircleFill,
  InfoCircleOutline,
  KeyOutline,
  LeftOutline,
  LoadingOutline,
  LockOutline,
  LogoutOutline,
  MailOutline,
  MenuOutline,
  MinusCircleFill,
  MinusCircleOutline,
  PhoneOutline,
  PictureOutline,
  PlusOutline,
  ReloadOutline,
  RightOutline,
  RobotOutline,
  SafetyCertificateFill,
  SafetyCertificateOutline,
  SafetyOutline,
  SearchOutline,
  SendOutline,
  SettingOutline,
  SolutionOutline,
  TeamOutline,
  ThunderboltFill,
  ThunderboltOutline,
  TranslationOutline,
  TrophyFill,
  TrophyOutline,
  UnorderedListOutline,
  UpOutline,
  UploadOutline,
  UserOutline,
  VideoCameraOutline,
  WarningFill,
  WarningOutline,
} from '@ant-design/icons-angular/icons';

export const BookmarkFill: IconDefinition = {
  name: 'bookmark',
  theme: 'fill',
  icon: '<svg viewBox="0 0 24 24" width="1em" height="1em" fill="currentColor"><path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"/></svg>'
};

export const BookmarkOutline: IconDefinition = {
  name: 'bookmark',
  theme: 'outline',
  icon: '<svg viewBox="0 0 24 24" width="1em" height="1em" fill="currentColor"><path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"/></svg>'
};

export const SunOutline: IconDefinition = {
  name: 'sun',
  theme: 'outline',
  icon: '<svg viewBox="0 0 24 24" width="1em" height="1em" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="5"></circle><line x1="12" y1="1" x2="12" y2="3"></line><line x1="12" y1="21" x2="12" y2="23"></line><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"></line><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"></line><line x1="1" y1="12" x2="3" y2="12"></line><line x1="21" y1="12" x2="23" y2="12"></line><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"></line><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"></line></svg>'
};

export const MoonOutline: IconDefinition = {
  name: 'moon',
  theme: 'outline',
  icon: '<svg viewBox="0 0 24 24" width="1em" height="1em" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"></path></svg>'
};

export const APP_ICONS: IconDefinition[] = [
  AlertFill,
  AlertOutline,
  ApartmentOutline,
  AppstoreOutline,
  ArrowLeftOutline,
  ArrowRightOutline,
  AuditOutline,
  BankOutline,
  BellOutline,
  BookFill,
  BookOutline,
  BookmarkFill,
  BookmarkOutline,
  BulbFill,
  BulbOutline,
  CalendarOutline,
  CarryOutOutline,
  CheckCircleFill,
  CheckCircleOutline,
  CheckOutline,
  ClearOutline,
  ClockCircleOutline,
  CloseCircleFill,
  CloseCircleOutline,
  CloseOutline,
  CloudUploadOutline,
  DashboardOutline,
  DeleteOutline,
  DollarOutline,
  DownOutline,
  EditOutline,
  EnvironmentOutline,
  ExportOutline,
  EyeInvisibleOutline,
  EyeOutline,
  FilePdfOutline,
  FileSearchOutline,
  FileTextOutline,
  FileWordOutline,
  FilterOutline,
  FundProjectionScreenOutline,
  GlobalOutline,
  HeartFill,
  HeartOutline,
  HomeOutline,
  InboxOutline,
  InfoCircleFill,
  InfoCircleOutline,
  KeyOutline,
  LeftOutline,
  LoadingOutline,
  LockOutline,
  LogoutOutline,
  MailOutline,
  MenuOutline,
  MinusCircleFill,
  MinusCircleOutline,
  PhoneOutline,
  PictureOutline,
  PlusOutline,
  ReloadOutline,
  RightOutline,
  RobotOutline,
  SafetyCertificateFill,
  SafetyCertificateOutline,
  SafetyOutline,
  SearchOutline,
  SendOutline,
  SettingOutline,
  SolutionOutline,
  TeamOutline,
  SunOutline,
  MoonOutline,
  ThunderboltFill,
  ThunderboltOutline,
  TranslationOutline,
  TrophyFill,
  TrophyOutline,
  UnorderedListOutline,
  UpOutline,
  UploadOutline,
  UserOutline,
  VideoCameraOutline,
  WarningFill,
  WarningOutline,
];
