#!/usr/bin/env python3
"""
Cursor IDE log scanner — extracts user prompts from local Cursor
agent transcripts into .ai-log/session.jsonl.

Source of truth:
    ~/.cursor/projects/<workspace-slug>/agent-transcripts/<conv_id>/<conv_id>.jsonl

Subagent transcripts are intentionally excluded: their `role == "user"`
messages are instructions generated by the parent agent, not prompts typed by
the human user.

Each transcript line is a JSON object. We emit one log entry per line where
`role == "user"`. The user query is extracted from the message content
(typically inside <user_query>...</user_query>).

Conversation -> repo mapping:
    1. Workspace slug matching: ~/.cursor/projects/<slug> where slug is derived
       from repo path (e.g. Users-admin-VinUni-P-164).
    2. Fallback: scanning transcript tool calls for paths matching repo root.

Deduplication:
    Avoids duplicate entries by checking existing `entry_id`s and
    (session_id, prompt) signatures in `.ai-log/session.jsonl` and
    `.ai-log/archive/*.jsonl` (covers prompts already captured by realtime hooks).

Usage:
    python scripts/log_cursor.py --auto            # default: last 24h
    python scripts/log_cursor.py --hours 72
    python scripts/log_cursor.py --all             # every conv, no cutoff
    python scripts/log_cursor.py --conv-id <id>    # one conversation
    python scripts/log_cursor.py --dry-run         # preview only

Env overrides:
    CURSOR_PROJECTS_DIR  point at a different projects/ directory
    AI_LOG_DIR           where session.jsonl is written (default: .ai-log)
"""
import argparse
import json
import os
import re
import subprocess
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

# Fix Windows console encoding so VN diacritics in prompts print cleanly.
if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

VN_TZ = timezone(timedelta(hours=7))
DEFAULT_CURSOR_PROJECTS = Path.home() / ".cursor" / "projects"

USER_QUERY_RE = re.compile(r"<user_query>(.*?)</user_query>", re.DOTALL)
TIMESTAMP_RE = re.compile(r"<timestamp>(.*?)</timestamp>", re.DOTALL)
IMAGE_FILES_RE = re.compile(r"<image_files>.*?</image_files>", re.DOTALL)


def git(cmd: str) -> str:
    try:
        return subprocess.check_output(
            cmd.split(), shell=False, text=True, stderr=subprocess.DEVNULL
        ).strip()
    except Exception:
        return ""


# ---------------------------------------------------------------------------
# Locating Cursor project directories & repo mapping
# ---------------------------------------------------------------------------

def _normalize(p: str) -> str:
    """Lower-case + backslash form, no trailing separator."""
    if not p:
        return ""
    return p.strip().lower().replace("/", "\\").rstrip("\\")


def _get_path_slug(p: Path) -> str:
    """Convert a path to Cursor project folder slug format.
    E.g. /Users/admin/VinUni/P-164 -> Users-admin-VinUni-P-164
         C:\\Users\\admin\\VinUni\\P-164 -> C-Users-admin-VinUni-P-164
    """
    s = str(p.resolve()).replace("\\", "/").lstrip("/")
    if len(s) >= 2 and s[1] == ":":
        s = s[0] + "-" + s[2:].lstrip("/")
    return s.replace("/", "-")


def get_cursor_project_dirs(repo_root: Path | None = None) -> list[Path]:
    """Find matching Cursor project directory for the repo."""
    env = os.environ.get("CURSOR_PROJECTS_DIR")
    base_dir = Path(env) if env else DEFAULT_CURSOR_PROJECTS
    if not base_dir.is_dir():
        return []

    if not repo_root:
        return [p for p in base_dir.iterdir() if p.is_dir()]

    slug = _get_path_slug(repo_root).lower()
    matched = []
    for p in base_dir.iterdir():
        if not p.is_dir():
            continue
        p_name = p.name.lower()
        if p_name == slug or p_name == repo_root.name.lower():
            matched.append(p)
        elif p_name.startswith(slug) or slug.startswith(p_name):
            matched.append(p)
    return matched


def _transcript_matches_repo(transcript: Path, repo_root_n: str) -> bool:
    """Check if tool call paths in transcript belong to repo."""
    if not repo_root_n or not transcript.is_file():
        return False
    try:
        with open(transcript, encoding="utf-8", errors="replace") as f:
            for line in f:
                if repo_root_n in _normalize(line):
                    return True
    except OSError:
        pass
    return False


# ---------------------------------------------------------------------------
# Prompt & timestamp extraction
# ---------------------------------------------------------------------------

def parse_cursor_timestamp(ts_str: str) -> str:
    """Parse Cursor timestamp string into ISO 8601 with VN_TZ.
    Example: 'Tuesday, Aug 18, 2026, 5:44 PM (UTC+7)' -> '2026-08-18T17:44:00+07:00'
    """
    if not ts_str:
        return ""
    ts_str = ts_str.strip()
    m = re.match(
        r"(?:[A-Za-z]+,\s+)?([A-Za-z]+)\s+(\d+),\s+(\d{4}),\s+(\d{1,2}):(\d{2})\s+(AM|PM)\s*\(UTC([+-]?\d+)?\)",
        ts_str,
        re.IGNORECASE,
    )
    if m:
        month_str, day_str, year_str, hour_str, min_str, ampm, tz_offset_str = m.groups()
        try:
            dt_base = datetime.strptime(
                f"{month_str} {day_str} {year_str} {hour_str}:{min_str} {ampm}",
                "%b %d %Y %I:%M %p",
            )
            offset_hours = int(tz_offset_str) if tz_offset_str else 0
            tz = timezone(timedelta(hours=offset_hours))
            dt = dt_base.replace(tzinfo=tz).astimezone(VN_TZ)
            return dt.isoformat()
        except ValueError:
            pass

    try:
        dt = datetime.fromisoformat(ts_str.replace("Z", "+00:00"))
        return dt.astimezone(VN_TZ).isoformat()
    except (ValueError, TypeError):
        return ""


def extract_user_prompt(msg: dict | str) -> tuple[str, str]:
    """Extract user prompt text and timestamp string from message dict or content.
    Returns (prompt_text, timestamp_iso).
    """
    raw_text = ""
    if isinstance(msg, dict):
        content = msg.get("content", "")
        if isinstance(content, list):
            for item in content:
                if isinstance(item, dict) and item.get("type") == "text":
                    raw_text += item.get("text", "") + "\n"
                elif isinstance(item, str):
                    raw_text += item + "\n"
        elif isinstance(content, str):
            raw_text = content
    elif isinstance(msg, str):
        raw_text = msg

    ts_iso = ""
    ts_match = TIMESTAMP_RE.search(raw_text)
    if ts_match:
        ts_iso = parse_cursor_timestamp(ts_match.group(1))

    # Remove image tags
    cleaned = IMAGE_FILES_RE.sub("", raw_text)
    cleaned = cleaned.replace("[Image]", "")

    query_match = USER_QUERY_RE.search(cleaned)
    if query_match:
        prompt = query_match.group(1).strip()
    else:
        prompt = TIMESTAMP_RE.sub("", cleaned).strip()

    return prompt, ts_iso


# ---------------------------------------------------------------------------
# Reading existing logs to avoid duplicates
# ---------------------------------------------------------------------------

def get_logged_signatures(log_dir: Path) -> tuple[set[str], set[tuple[str, str]]]:
    """Read existing entry_ids and (session_id, prompt) signatures from
    session.jsonl and all archive files.
    """
    logged_ids: set[str] = set()
    logged_prompts: set[tuple[str, str]] = set()

    files_to_check: list[Path] = []
    live_file = log_dir / "session.jsonl"
    if live_file.exists():
        files_to_check.append(live_file)

    archive_dir = log_dir / "archive"
    if archive_dir.is_dir():
        files_to_check.extend(archive_dir.glob("*.jsonl"))

    for fpath in files_to_check:
        try:
            with open(fpath, encoding="utf-8-sig", errors="replace") as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        entry = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    eid = entry.get("entry_id", "")
                    if eid:
                        logged_ids.add(eid)
                    sid = entry.get("session_id", "")
                    prompt = entry.get("prompt", "").strip()
                    if sid and prompt:
                        # Normalize prompt snippet for matching against realtime hook entries
                        logged_prompts.add((sid, prompt[:200]))
        except OSError:
            pass

    return logged_ids, logged_prompts


# ---------------------------------------------------------------------------
# Iterating user inputs from Cursor transcripts
# ---------------------------------------------------------------------------

def iter_user_inputs(project_dirs: list[Path], cutoff: datetime | None,
                      only_conv: str | None, repo_root_n: str):
    """Yield user-input dicts from all matching Cursor transcript files."""
    for pdir in project_dirs:
        transcript_dir = pdir / "agent-transcripts"
        if not transcript_dir.is_dir():
            continue

        # Only read the top-level conversation transcript. Files below a
        # subagents/ directory can contain agent-generated tasks represented
        # as role=user and must never be counted as human prompts.
        for transcript in sorted(transcript_dir.glob("*/*.jsonl")):
            if not transcript.is_file() or transcript.stat().st_size == 0:
                continue

            conv_id = transcript.stem
            if only_conv and conv_id != only_conv:
                continue

            # If repo filter is active, check directory match or tool calls
            if repo_root_n and not _transcript_matches_repo(transcript, repo_root_n):
                # Also check if parent directory slug matched
                slug = _get_path_slug(Path.cwd()).lower()
                if pdir.name.lower() != slug and pdir.name.lower() != Path.cwd().name.lower():
                    continue

            file_mtime = datetime.fromtimestamp(
                transcript.stat().st_mtime, tz=VN_TZ
            )

            try:
                with open(transcript, encoding="utf-8", errors="replace") as f:
                    for line_idx, line in enumerate(f):
                        line = line.strip()
                        if not line:
                            continue
                        try:
                            entry = json.loads(line)
                        except json.JSONDecodeError:
                            continue

                        if entry.get("role") != "user":
                            continue

                        prompt_text, ts = extract_user_prompt(
                            entry.get("message", {})
                        )
                        if len(prompt_text) < 2:
                            continue

                        # Determine effective timestamp for cutoff check
                        entry_dt = file_mtime
                        if ts:
                            try:
                                entry_dt = datetime.fromisoformat(ts)
                            except ValueError:
                                pass

                        if cutoff and entry_dt < cutoff:
                            continue

                        yield {
                            "conv_id": conv_id,
                            "step_index": line_idx,
                            "timestamp": ts or entry_dt.isoformat(),
                            "text": prompt_text,
                        }
            except OSError:
                pass


# ---------------------------------------------------------------------------
# Emitting entries
# ---------------------------------------------------------------------------

def build_entry(msg: dict, repo: str, branch: str, commit: str,
                student: str) -> dict:
    return {
        "ts": msg["timestamp"],
        "tool": "cursor",
        "event": "UserPrompt",
        "entry_id": f"cursor-{msg['conv_id']}-{msg['step_index']:05d}",
        "session_id": msg["conv_id"],
        "model": "cursor",
        "repo": repo,
        "branch": branch,
        "commit": commit,
        "student": student,
        "prompt": msg["text"],
        "response_summary": "",
    }


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Extract user prompts from Cursor IDE transcripts"
                    " into .ai-log/session.jsonl."
    )
    parser.add_argument("--auto", action="store_true",
                        help="Default mode: scan recent conversations.")
    parser.add_argument("--hours", type=int, default=24,
                        help="Window in hours when scanning (default: 24).")
    parser.add_argument("--all", action="store_true",
                        help="Ignore the time window; scan everything.")
    parser.add_argument("--conv-id",
                        help="Limit to a single conversation id.")
    parser.add_argument("--no-repo-filter", action="store_true",
                        help="Don't filter conversations by current repo.")
    parser.add_argument("--dry-run", action="store_true",
                        help="Show what would be logged, don't write.")
    args = parser.parse_args()

    repo_root = Path.cwd()
    project_dirs = get_cursor_project_dirs(
        None if args.no_repo_filter else repo_root
    )

    if not project_dirs:
        print("[cursor-log] No Cursor project directories found "
              f"at {DEFAULT_CURSOR_PROJECTS}.", file=sys.stderr)
        sys.exit(0)

    log_dir = Path(os.environ.get("AI_LOG_DIR", ".ai-log"))
    log_dir.mkdir(exist_ok=True)
    log_file = log_dir / "session.jsonl"
    logged_ids, logged_prompts = get_logged_signatures(log_dir)

    cutoff = None
    if not args.all:
        cutoff = datetime.now(tz=VN_TZ) - timedelta(hours=args.hours)

    repo_root_n = "" if args.no_repo_filter else _normalize(str(repo_root))

    repo = git("git remote get-url origin").split("/")[-1].replace(".git", "")
    branch = git("git rev-parse --abbrev-ref HEAD")
    commit = git("git rev-parse --short HEAD")
    student = git("git config user.email") or os.environ.get(
        "USERNAME", os.environ.get("USER", "unknown")
    )

    new_entries: list[dict] = []
    for msg in iter_user_inputs(project_dirs, cutoff, args.conv_id, repo_root_n):
        entry = build_entry(
            msg, repo or repo_root.name, branch, commit, student
        )
        if entry["entry_id"] in logged_ids:
            continue
        # Also check if prompt was already captured by realtime hook
        sig = (entry["session_id"], entry["prompt"][:200].strip())
        if sig in logged_prompts:
            continue

        new_entries.append(entry)
        logged_ids.add(entry["entry_id"])
        logged_prompts.add(sig)

    if not new_entries:
        scope = "all" if args.all else f"{args.hours}h"
        repo_note = "any repo" if args.no_repo_filter else f"repo={repo_root_n or '(unknown)'}"
        print(f"[cursor-log] No new prompts ({repo_note}, window={scope}).",
              file=sys.stderr)
        sys.exit(0)

    if args.dry_run:
        print(f"\n[cursor-log] DRY RUN — would log "
              f"{len(new_entries)} entries:\n")
        for e in new_entries:
            preview = e["prompt"].replace("\n", " ")[:120]
            print(f"  [{e['ts'][:19]}] {preview}")
        sys.exit(0)

    with open(log_file, "a", encoding="utf-8") as f:
        for e in new_entries:
            f.write(json.dumps(e, ensure_ascii=False) + "\n")

    print(f"[cursor-log] Logged {len(new_entries)} prompt(s) from "
          f"Cursor IDE.", file=sys.stderr)


if __name__ == "__main__":
    main()
